In [1]:
import numpy as np

In [4]:
"""
This is how arange function is used.
The 1st argument which is 1 is the starting point of the array which is to be generated.
The 2nd argument which is 11 is the ending point of the array which is to be generated. Also it is not included in the array which is generated.
The 3rd argument which is 1.5 is optional and determines the difference between 2 values in the array which is to be generated.
The 4th argument which is dtype is also optional and determines the data type of the numbers of the array which is to be generated.
"""

np.arange(1,11,1.5,dtype='float')

array([ 1. ,  2.5,  4. ,  5.5,  7. ,  8.5, 10. ])

In [8]:
"""
It is similar to arange but there are slight differences:
1) Here the 2nd argument which is 11 is included in the array which is to be generated.
2) Here the 3rd argument which is 5 determines the number of elements we want between the range, it do not determines the difference between the numbers of the array which is to be generated.

It is used to generate numbers which are equispaced but we cannot define the difference between the numbers we can only define the number of numbers we want in the array which is to be generated.
"""

np.linspace(1,11,5,dtype='int')

array([ 1,  3,  6,  8, 11])

In [10]:
# Both does the same thing which is to import the random module.

import random
from numpy import random

In [21]:
# This generates a numpy array which random floating point numbers between 0 to 1.

np.random.rand(3,2)

array([[0.02243835, 0.86632795],
       [0.40356299, 0.75704442],
       [0.47097239, 0.90893136]])

In [30]:
# This is used to generate a random number between the range given in the parameter.

np.random.randint(1,100)

40

In [35]:
"""
This is used to generate floating point number between the range given in the argument.
By the number we divide generates the number after the point.
"""

print(np.random.randint(1,10)/10)
print(np.random.randint(1,10)/1000)

0.4
0.008


In [39]:
# range is basically a iterator which we use in a loop like for loop.

print(range(1,10))
print(range(3,))

range(1, 10)
range(0, 3)


In [45]:
"""
This generates a array of zeroes.
By default the data type is of floating point but we can explicitly define it as int.
"""

np.zeros([3,2], dtype='int')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [49]:
# It is similar to zeros the only difference is it prints 1s instead of 0s.

np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
# This basically repeats the array the number of times we define.

np.tile([1,2,3],3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [54]:
# It is similar to tile but the difference is it repeats the number instead of the array itself.

np.repeat([1,2],5)

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2])