In [1]:
import numpy as np

In [2]:
a =  np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [5]:
a.ndim

2

In [39]:
b = np.array([1, 2, 3, 4, 5])
c = np.array([10, 9, 8, 7, 6])
b, c

(array([1, 2, 3, 4, 5]), array([10,  9,  8,  7,  6]))

In [44]:
# The concatenate function is used to concatenate 2 arrays.

d = np.concatenate([b, c])
d

array([ 1,  2,  3,  4,  5, 10,  9,  8,  7,  6])

In [49]:
# This is how we sort the array.

d.sort()
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
# This will throw an error because we cannot concatenate 2 arrays which are different in dimensions.

e = np.concatenate([a,b])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [86]:
# So we need to convert b to a 2D array.

b = np.array([1, 2, 3, 4, 5])
b
f = np.array(b).reshape(-1,1)
f.ndim

2

In [101]:
"""
If anywhere we specify the value as -1 then it finds out the best dimension of the array.
Instead of -1 we could have wrote 1 but the result will be same as the it is only dimension the array can exist after concatenation.
"""

a = np.array(a).reshape(-1,2)
a
e = np.concatenate([f,a], axis=-1)
e

array([[ 1,  1,  2],
       [ 2,  3,  4],
       [ 3,  5,  6],
       [ 4,  7,  8],
       [ 5,  9, 10]])

In [112]:
"""
This is how vertically stack arrays using vstack function.
For this we need equal number of columns.
"""
a=a.reshape(-1,1)
np.vstack([f,a])

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [116]:
"""
This is how we do horizontal stacking.
We need to have equal number of rows here.
"""

a=a.reshape(5,2)
np.hstack([f,a])

array([[ 1,  1,  2],
       [ 2,  3,  4],
       [ 3,  5,  6],
       [ 4,  7,  8],
       [ 5,  9, 10]])