In [1]:
import numpy as np

In [51]:
"""
np.nan: in numpy nan stands for not a number which means a datatype which numpy cannot understand.
np.inf: in numpy inf stands for infinite which means it is beyond its capabilities to perform calculations on that.
"""

'\nnp.nan: in numpy nan stands for not a number which means a datatype which numpy cannot understand.\nnp.inf: in numpy inf stands for infinite which means it is beyond its capabilities to perform calculations on that.\n'

In [55]:
# We cannot compare 2 nan

np.nan==np.nan, np.nan>np.nan, np.nan<np.nan

(False, False, False)

In [57]:
# But we can compare inf

np.inf == np.inf, np.inf > np.inf, np.inf < np.inf

(True, False, False)

In [58]:
# There is None Data type also which we compare only == and not > or <

None==None

True

In [60]:
# This will throw an error

None>None

TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'

In [63]:
# This shows that nan is of float type so it is of 64 bits so we cannot directly convert any integer to nan, we need to convert it to float and then nan.

a = np.nan

type(a)

float

In [69]:
a = np.array([[1,2,3],[4,5,6]], dtype='f')
a.shape, a.dtype, a

((2, 3),
 dtype('float32'),
 array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32))

In [68]:
# This will throw an error initially as we have not converted int to floatL

a[0][1] = np.nan
a[0][2] = np.inf

ValueError: cannot convert float NaN to integer

In [71]:
# Now it will not throw an error because now we have converted int to float and then we convert the floating point numbers to nan.

a[0][1] = np.nan
a[0][2] = np.inf

In [74]:
# This we replace all the numbers will boolean values and the place which had nan will be shown as 'True'.

np.isnan(a)

array([[False,  True, False],
       [False, False, False]])

In [75]:
# This we replace all the numbers will boolean values and the place which had inf will be shown as 'True'.

np.isinf(a)

array([[False, False,  True],
       [False, False, False]])