In [1]:
import numpy as np

In [3]:
np.__version__

'2.0.2'

In [7]:
# This creates a numpy array. It can be a list, tuple, etc.
a = np.array([1,2,3])

In [8]:
a

array([1, 2, 3])

In [11]:
# This will show that `a` is a type of numpy array.
type(a)

# ndarray means n dimensional array.

numpy.ndarray

In [13]:
# This will print basically the size of the array.
a.shape

(3,)

In [15]:
# This will give the dimension of the array.
a.ndim

1

In [18]:
b = np.array((1,2,3))

# This will give the same result as the results before which was for an array instead here we have used tuple here.
b, type(b), b.shape, b.ndim

(array([1, 2, 3]), numpy.ndarray, (3,), 1)

In [22]:
# 0 dimensional array

c = np.array(1)

# Here the c.shape gives nothing because a single number is a scalar and not a vector therefore it has no dimension. Since it has no dimension the size of the that dimension cannot be obtained.
c, type(c), c.shape, c.ndim

(array(1), numpy.ndarray, (), 0)

In [24]:
# 2 dimensional array

d = np.array([[1,2,3],[4,5,6]])

"""
Here for d.shape we get 2 values which is (2,3).
The 2 shows the number of rows and 3 shows the number of columns.
"""
d, type(d), d.shape, d.ndim

(array([[1, 2, 3],
        [4, 5, 6]]),
 numpy.ndarray,
 (2, 3),
 2)

In [34]:
# 3 dimensional array

e = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

"""
This shows that 3 dimensional array is a list of 2 dimensional array.
Similarly n dimensional array is a list of n-1 dimensional array.
Also, Here e.shape prints 2,2,3 which means there are 2 arrays in which there are 2 rows with 2 columns each.
Also, to get the number of dimensions just count the number of opening brackets or closing brackets.
In our case there are 3 opening and closing brackets therefore the number of dimensions is 3.
"""
e, type(e), e.shape, e.ndim

(array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]]),
 numpy.ndarray,
 (2, 2, 3),
 3)

In [35]:
# We can do this as well instead of writing e.ndim as both gives the number of dimensions.

len(e.shape)

3