In [1]:
import numpy as np

In [48]:
"""
Data Types in Numpy:
1) integer - i
2) boolean - b
3) unsigned integer - u
4) float - f
5) complex float - c
6) timedelta - m
7) datetime - M
8) object - O
9) string - S
10) unicode string - U
11) fixed chunk of memory for other type (void) - V

unsigned integers are integers without sign which means the range of unsigned integer is 0 to 65535 if we are using 16 bits of int type and if we are using 32 bits of int type then the range is 0 to 4,294,967,295.
timedelta is a data which tells us the difference of time.
object is a datatype which is used for any kind of data which is unknow to numpy.
Unicode string is a sequence of characters where each character corresponds to a unique number, called a code point, defined by the Unicode standard.
"""

'\nData Types in Numpy:\n1) integer - i\n2) boolean - b\n3) unsigned integer - u\n4) float - f\n5) complex float - c\n6) timedelta - m\n7) datetime - M\n8) object - O\n9) string - S\n10) unicode string - U\n11) fixed chunk of memory for other type (void) - V\n\nunsigned integers are integers without sign which means the range of unsigned integer is 0 to 65535 if we are using 16 bits of int type and if we are using 32 bits of int type then the range is 0 to 4,294,967,295.\ntimedelta is a data which tells us the difference of time.\nobject is a datatype which is used for any kind of data which is unknow to numpy.\nUnicode string is a sequence of characters where each character corresponds to a unique number, called a code point, defined by the Unicode standard. \n'

In [5]:
a = np.array([1,2,3,4])
a, a.dtype

(array([1, 2, 3, 4]), dtype('int64'))

In [7]:
# Here in a numpy if there is a single number which is of floating point then it converts all the rest of the numbers to floating point. Also in python we represent floating point numbers which has 0 after the point like this number. we do not write the 0 after the point.

b = np.array([1,2,3,4.0])
b, b.dtype

(array([1., 2., 3., 4.]), dtype('float64'))

In [9]:
# Here we can see that the datatype shows that U6 where U means unicode but the 6 here means is that the longest word in the array (in our case it is banana which has a length of 6 that is why we are getting U6).

c = np.array(['apple', 'banana'])
c

array(['apple', 'banana'], dtype='<U6')

In [11]:
"""
Here we convert the words from unicode string to normal string as it shows the dtype as '|S7'.
It shows 7 because the longest sequence of characters is 'bananas' which is 7.
"""

d = np.array(['apple', 'bananas'], dtype='S')
d

array([b'apple', b'bananas'], dtype='|S7')

In [13]:
# This will throw an error because we are trying to convert a string to an integer.

e = np.array(['apple', 'bananas'], dtype='i')
e

ValueError: invalid literal for int() with base 10: 'apple'

In [15]:
# Here i4 means integer type of 4 byte which is of 32 bits that is why we get dtype as 'int32'.

f = np.array(['0', '1'], dtype='i4')
f

array([0, 1], dtype=int32)

In [18]:
# Here i1 means integer type of 1 byte which is of 8 bits that is why we get dtype as 'int8'.

g = np.array(['0', '1'], dtype='i1')
g

array([0, 1], dtype=int8)

In [22]:
# This will throw an error because integer can be of size 1 byte, 2 bytes, 4 bytes and 8 bytes.

h = np.array(['0', '1'], dtype='i3')
h

TypeError: data type 'i3' not understood

In [24]:
# This is how we define floating point datatype in numpy array.

i = np.array(['0.2', '1'], dtype='f')
i

array([0.2, 1. ], dtype=float32)

In [25]:
# This is will throw an error as we cannot directly convert float to int in python.

j = np.array(['0.2', '1'], dtype='i')
j

ValueError: invalid literal for int() with base 10: '0.2'

In [27]:
# This is how we convert float to int in numpy array.

i.astype('i')

array([0, 1], dtype=int32)

In [44]:
"""
We can do other conversions also like here we are converting to string type.
We get 32 at the end of S32 as the size of the float datatype is of 32 bits.
"""

i.astype('S')

array([b'0.2', b'1.0'], dtype='|S32')

In [45]:
# converting to boolean.

i.astype('bool')

array([ True,  True])

In [46]:
# converting to unicode string.

i.astype('str')

array(['0.2', '1.0'], dtype='<U32')

In [47]:
# Sorting of an numpy array

l = np.array([1,5,3,7,2])
print(l)
l.sort() # Sorts in ascending order
print(l)
print(-np.sort(-l)) # There is no built in method for sorting in descending order in numpy so this is how we do sorting in descending order in a numpy array.

[1 5 3 7 2]
[1 2 3 5 7]
[7 5 3 2 1]
