In [1]:
import numpy as np

In [2]:
a =  np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [5]:
a.ndim

2

In [8]:
# This saves the array as a binary numpy format.

np.save('a.npy', a)

In [10]:
"""
This saves the array in a text file.
Delimiter determines how to separate the values in a array.
"""

np.savetxt('a.txt', a, delimiter=',')

In [14]:
b = np.array([a, a])
b.ndim

3

In [17]:
# This saves the file as a csv binary numpy format.

np.savetxt('a.csv', a)

In [18]:
# This will throw an error because csv can store 2D array values and not 3D array values.

np.savetxt('b.csv', b)

ValueError: Expected 1D or 2D array, got 3D array instead

In [19]:
# So we have to store it in a binary numpy array format.

b = np.save('b.npy', b)

In [21]:
"""
Loading the data from files.

The 'loadtxt' function converts the data to a floating point datatype if it is in a int datatype.
"""

print(np.loadtxt('a.txt', delimiter=','))

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [25]:
# This will throw an error because it can load only binary numpy format unless the file is specified to load by other functions.

print(np.load('a.txt'))

ValueError: Cannot load file containing pickled data when allow_pickle=False

In [27]:
# The 'load' function do not change the datatype to floating point type rather it keeps the data as it is.

print(np.load('a.npy'))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
"""
This saves the file in npz format.
Also it is used to save multiple numpy arrays together without concatenating them.
"""

np.savez('together.npz', a, b)

In [30]:
"""
This shows the arrays which are stored in the file but not their content.
For fetching the content we need to use the indexes to get the data.
"""

print(np.load('together.npz'))

NpzFile 'together.npz' with keys: arr_0, arr_1


In [38]:
# This is how we get the value for the arrays in a file of npz type.

c = np.load('together.npz')
print(c.files)
c['arr_0']

['arr_0', 'arr_1']


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])