In [1]:
import numpy as np

In [3]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [7]:
# ndim gives the dimension of the array

a.ndim, a.shape

(2, (2, 5))

In [8]:
# "reshape" is used to reshape the array. We need to be careful when doing the reshaping because the product of rows and columns of the reshape must be equal to the product of the rows and column before reshaping.

a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [10]:
# This will throw error because the product of the rows and columns of the reshape does not equal to the product of the rows and columns matrix before reshaping.

a.reshape(3,5)

ValueError: cannot reshape array of size 10 into shape (3,5)

In [12]:
# In place of columns I wrote -1 which means you can make any number of columns only if the product of the rows and columns of the reshape is equal to the product of the rows and column before reshaping.

a.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [15]:
# This converts any dimension array to a 1D array but it return a view which means the original array is changed.

a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
# This is similar to ravel the only difference is that it returns a copy and do not change the original array.

a.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])