In [1]:
import numpy as np

In [58]:
a=np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [60]:
# This does not returns the value rather it returns the indexes where the values are greater than 10

np.where(a>10)

(array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [62]:
# it will throw an error as it expects only 1 argument and not 2.

np.where(a>10 and a<5)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [72]:
"""
To do this type of operation then we need to do it in 2 steps:
1) First get the values for the 1st condition.
2) Second get the values for the 2nd condition.
"""


b = np.where(a<10)
c =  a[b]
print(c)
d = np.where(c>5)
print(c[d])

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]


In [74]:
# This displays the index of the stacked array which contains the max value.

a.argmax()

np.int64(19)

In [76]:
# This will throw an error because as argmax returns the index in terms of stacked array.

a[a.argmax()]

IndexError: index 19 is out of bounds for axis 0 with size 2

In [78]:
# It is similar to argmax the only difference is it returns the index of the minimum number in terms of stacked array.

a.argmin()

np.int64(0)

In [80]:
# This will return the max value in the array.

a.flatten()[a.argmax()], a.max()

(np.int64(20), np.int64(20))

In [81]:
a.flatten()[a.argmin()], a.min()

(np.int64(1), np.int64(1))